### PR TITLE
Dogbin support for paste, updater toggling

### PR DESCRIPTION
**Pull request by zakaryan2004**
Added dogbin to the paste command, added support for dogbin shortened URLs and added get_dogbin_content command.

Credits:
@deletescape for dogbin(Thx!) and Python implelemtation in SkittBot

### CODE REVIEW

**Comment by zakaryan2004** [comment]
DO NOT MERGE. Have found a little problem with heroku which I will fix and push a new commit. Will test too

**Comment by baalajimaestro** [comment]
@Yasir-siddiqui .approve

**Comment by Yasir-siddiqui** [comment]
.disapprove

**Comment by Yasir-siddiqui** [comment]
Bhai kab Pr Accept karega .__.

**Pull request merged**
