### PR TITLE
Use python-dotenv for configuration. Better compatibility between heroku and other servers

### PR DESCRIPTION
**Pull request by nitanmarcel**
Replaced config.py with config.ini so I was able to make the script ask the user for their config settings. This would make launching the userbot easier.

Documentation about configparser and how to add/get values from config.ini are available at: https://wiki.python.org/moin/ConfigParserExamples  

Please test the code first and tell me if anything is wrong. Maybe I forgot something.

### CODE REVIEW

**Comment by nitanmarcel** [comment]
Useful, as would get rid of some of this code and the code from heroku maybe?

**Comment by deletescape** [comment]
Yes, it would take the heavy lifting off supporting both env var configuration and file based config

**Comment by baalajimaestro** [comment]
@nitanmarcel Sure. Thanks. I would take time to merge this. Coz I might need to make suitable changes for the code to use the new dot-env thingies

**Comment by baalajimaestro** [comment]
@deletescape Thanks for suggesting python-dotenv, it indeed seems way better than the current implementation. Many actually had issues with config.py

**Pull request merged**
