### PR TITLE
binary stuff

### PR DESCRIPTION
**Pull request by LifeIsWar**
binary stuff

### CODE REVIEW

**Comment by raphielscape** [comment]
Unrecognizable License, dropped due to license model seems not following any of available license, or neither dual-licensed

**Comment by LifeIsWar** [comment]
lol

**Comment by raphielscape** [comment]
Please link for the LICENSE of yours, i'll check if your license is compatible with our license or this should've dual licensed

Thanks

**Comment by zakaryan2004** [comment]
> Please link for the LICENSE of yours, i'll check if your license is compatible with our license or this should've dual licensed
> 
> Thanks

It needs to exist 🤣

**Pull request closed without merging**
