### PR TITLE
Use SQL as session database if the DB_URI is specified

### PR DESCRIPTION
**Pull request by nitanmarcel**
Use SQL as session database if the DB_URI is specified. This will switch to a different session so reconnecting with the TG account is required as the old session will not be used. This will be only required just at the first start after using the new session.

The session can be deleted at any time using `python3 -m -d` or `python3 -m --delete`

The pro of this method is that there won't be any problems while using this userbot on heroku-like servers.

The old session will still be available for  users running in Non-SQL mode

### CODE REVIEW

**Comment by nitanmarcel** [comment]
It does the same thing the __init__.py in the SQL does: trow an error if is not correct.

**Comment by baalajimaestro** [comment]
Put up some exception handler to show up a decent Error message plox

**Comment by nitanmarcel** [comment]
It will tell the user that it can't connect to the database and it will close the app... There's no reason to catch any exceptions because that behaviour is expected if the URL format is not correct. From my point of view

**Comment by baalajimaestro** [comment]
@nitanmarcel Ok. Cool then. Will merge ._.

**Pull request merged**
