### PR TITLE
Add Youtube Search module

### PR DESCRIPTION
**Pull request by zakaryan2004**

### CODE REVIEW

**Comment by baalajimaestro** [comment]
@zakaryan2004 I'll check  b4 merging. Please bear with delay.

**Comment by nitanmarcel** [comment]
Bad chose.. they will restain you from any rights you have for the code like they did with me -_- check my pull request

**Comment by baalajimaestro** [comment]
@nitanmarcel > report spam

**Comment by nitanmarcel** [comment]
I did the same with you don't worry

**Comment by raphielscape** [comment]
> Bad chose.. they will restain you from any rights you have for the code like they did with me -_- check my pull request

We already did following your requirements and removed your code entirely, spamming on other PR isn't going to make a unicorn comes to your bathroom

**Pull request merged**
