### PR TITLE
Fix Typewriter, K

### PR DESCRIPTION
**Pull request by shanuflash**

### CODE REVIEW

**Comment by baalajimaestro** [comment]
@shanuflash Can't merge ._. Travelling on 2G lol

**Comment by shanuflash** [comment]
@baalajimaestro lelmao

**Comment by shanuflash** [comment]
@baalajimaestro merge?

**Comment by shanuflash** [comment]
@baalajimaestro O.o

**Comment by baalajimaestro** [comment]
@shanuflash Will fix. Busy on other meme fixes.

**Pull request closed without merging**
