### PR TITLE
[FINISHED] Python 3.8 deployment for Docker

### PR DESCRIPTION
**Pull request by peaktogoo**

### CODE REVIEW

**Comment by baalajimaestro** [comment]
@peaktogoo Inb4 time to compile results in too much waiting for deploy, also we currently don't need any of those features in 3.8 badly.

**Comment by raphielscape** [comment]
Please check for deployment time regression first

**Comment by peaktogoo** [comment]
Imma fix GCC problem

**Comment by peaktogoo** [comment]
Work finished

**Pull request merged**
