### PR TITLE
Dockerfile: Use Alpine Linux Packaged Python3

### PR DESCRIPTION
**Pull request by Akianonymus**
* the current way is crap, takes too much time.

* This setup Python 3.6.8

Time taken :-

	Before:
		real 7m20.811s
		user 0m0.356s
		sys 0m0.303s

	After:
		real 2m23.381s
		user 0m0.166s
		sys 0m0.116s

### CODE REVIEW

**Comment by peaktogoo** [comment]
First, on the current Dockerfile, you have full option to choose python version to your 3.6 is useless. Second, i use pyenv for python and that's why it take time.

**Comment by peaktogoo** [comment]
Do not merge

**Comment by Akianonymus** [comment]
I wrote the python version so everyone could know, this pr is not about it.

Yes, it takes time for a useless thing

If it's working like this, then no sense to use a time taking way.

And don't throw me the shit that pyenv/py3.8 is good/updated or whatever, it is what it is.

**Comment by Akianonymus** [comment]
and remove or fix this semaphore ci test, ffs.

**Comment by raphielscape** [comment]
> and remove or fix this semaphore ci test, ffs.

Baalaji is the one who can changes the CI mechanics for Pull Requests

**Comment by raphielscape** [comment]
Alpine's Python is currently Outdated, so this PR will keep opened until there's solution from Alpine's upstream, thanks

**Comment by Akianonymus** [comment]
waiting forever

**Comment by raphielscape** [comment]
Move this to Staging, this Pull is now considered valid as Alpine Python3 package is currently on 3.7.8, Closing this as new pull are required.

**Pull request closed without merging**
