### PR TITLE
readme file update

### PR DESCRIPTION
**Pull request by leviathanaxeislit**

### CODE REVIEW

**Comment by baalajimaestro** [comment]
What is this PR even for?
Why you want to merge back to source?

**Comment by baalajimaestro** [comment]
Closed kek.

**Comment by leviathanaxeislit** [comment]
> What is this PR even for?
> Why you want to merge back to source?

i guess this was in the beginning when we were testing it

**Comment by songotenks69** [comment]
@leviathanaxeislit Have you never seen PRs on Marie?

**Comment by songotenks69** [comment]
Wait that's wrong tag , bitch what the fuck githubbot

**Comment by raphielscape** [comment]
but why it's up again

**Pull request closed without merging**
