### PR TITLE
Depleting two files pushed by me because of the GPL license violation

### PR DESCRIPTION
**Pull request by nitanmarcel**
Deleting two files pushed by me because of the GPL license violation. These files have code that was pushed by me when the project was licenses under GPL and no one asked my approval to put it under the RPL license. I ask these files to be deleted from the project and if it contains code made by you and it doesn't have parts of my code (xpic) I suggest you to only delete my code and his derivates.

Thanks

### CODE REVIEW

**Comment by baalajimaestro** [comment]
-2 don't submit this

**Comment by raphielscape** [comment]
Removed package module at commit https://github.com/baalajimaestro/Telegram-UserBot/commit/4002d05ba3a6a97397eecc90f3ad0033683c3b0d , for profile module, we decided to drop this under RPL Clause 4 for Dual-Licensing at commit https://github.com/baalajimaestro/Telegram-UserBot/commit/a79fd74d145db91e981915fc44e23f55170fa7c2 , profile module will be rewritten later

**Comment by baalajimaestro** [comment]
@raphielscape Wao

**Comment by raphielscape** [comment]
Speaking of act, GPLv3 is a copyleft license, yet we already did complying by Dual-Licensing it, so you can't remove it altogether in this upstream regardless your "ownership" of the code

> Because a developer had given permission for their code to be used doesn't mean that it's a permanent, non-irrevocable grant. This addresses the estoppel defense. In its simplest form, once the code has been given, _Paperplane Project_ can reasonably rely that the developer won't damage _Paperplane Project_ by taking back the right to use the code.

**Comment by raphielscape** [comment]
But still, we'll rewrite that and drop it fully under RPL regardless of our GPLv3 complying in this case.

**Comment by nitanmarcel** [comment]
@raphielscape Ok. I'm waiting for the code to be rewriten. As for the RPL  because the license is homemade and there's no full document saying that the license is registered anywhere and it was not made following the legal terms and without consulting a lawyer while doing the license. Also the full license is missing from the LICENSE.md for the users won't be able to know what rights they have when using the project licensed under your RPL license thus from my point of view making ilthe project unlicensed

Also speaking of the code that was part of the GPL license this PR was made before the dual licencing and you still violated the GPL license before this PR. And as a contributor I wasn't asked if I want to license my apart of the code under RPL license.

**Comment by raphielscape** [comment]
LICENSE.md is basically the summary of the LICENSE.full, we didn't publicizing the full license as it's not required for now, also the main use of this license is covered under my company licensing anyway.

RPL isn't Homemade due to it's my Company License, we did consulting to lawyers when doing the license, it's following legal terms because Raphielscape Public License is part of The Raphielscape Company Licensing Infrastructure, and the core Raphielscape License is used only for my Company use.

OSPRPL (Open Source Projects Raphielscape Public License) is a branch of the core Raphielscape License that used for Open Source Projects that covered by Raphielscape Open Source Holding LLC.

And about the code-revoking, as cited in GPL Copyleft Grants : 

> Once the code has been given, that respective project can reasonably rely that the developer won't damage that respective project by taking back the right to use the code.

**Comment by nitanmarcel** [comment]
Permit me to send you the link for the full GPLV3 document and let you quote me from there the text you just quoted in your comment: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext

**Comment by raphielscape** [comment]
It’s also worth mentioning that the concept of “Promissory Estoppel” could come into play; which essentially prevents an individual from going back on a promise if the other party took action based on that promise. In other words, if you told somebody they could use your code and they used it to produce a successful project, you can’t then go back on that promise because it would be to their detriment.

**Comment by nitanmarcel** [comment]
Has been a day and the code is still the same. I can't imagine the missing respect that you kids have by just editing the license and laughing in my face afterwards. I really think this is unacceptable and I refuse to not do something about it.

Thanks

**Comment by raphielscape** [comment]
Fully closing this issue in commit https://github.com/baalajimaestro/Telegram-UserBot/commit/1a14fd82d8d1cacf351e346239d6d270084c6a81

**Pull request closed without merging**
