### PR TITLE
Automated system packages installation

### PR DESCRIPTION
**Pull request by nitanmarcel**
This will install any system packages (neofetch for example) when the bot starts.

### CODE REVIEW

**Comment by nitanmarcel** [comment]
@baalajimaestro I already said in chat how to install packages on heroku. More exactly I saved a note #neofetch that has instructions on how to install that on heroku.

For heroku this [apt builback](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt) is needed

**Comment by Yash089610** [comment]
@nitanmarcel would this installation be performed everytime bot starts?

**Comment by baalajimaestro** [comment]
@Yash089610 Indeed yes

**Comment by Yash089610** [comment]
I don't think it's needed everytime on a local PC or VM instance @baalajimaestro ... Just like extra startup time... U can add in readme to install them seperately

**Comment by nitanmarcel** [comment]
@Yash089610 @baalajimaestro  Doesn't add to much to the uptime..  And test the process starts at every startup but won't download anything if the file exists...  Just if is not available or if there's an update

**Pull request merged**
