### PR TITLE
Fix gmute

### PR DESCRIPTION
**Pull request by Dyneteve**

### CODE REVIEW

**Comment by raphielscape** [comment]
It's fixed on Staging but it's not merged up to master yet

**Comment by raphielscape** [comment]
Closing this for now

**Comment by baalajimaestro** [comment]
@Dyneteve When was gmute broken?

**Comment by raphielscape** [comment]
It's broke at the refactor

**Comment by raphielscape** [comment]
Seems like the staging branch with the fix is ready to be introduced to master

**Pull request closed without merging**
